# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setup.ui'
#
# Created: Tue Oct 20 23:28:32 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_setupDlg(object):
    def setupUi(self, setupDlg):
        setupDlg.setObjectName(_fromUtf8("setupDlg"))
        setupDlg.resize(401, 418)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(setupDlg.sizePolicy().hasHeightForWidth())
        setupDlg.setSizePolicy(sizePolicy)
        setupDlg.setSizeGripEnabled(False)
        self.gridLayout = QtGui.QGridLayout(setupDlg)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.setupLayout = QtGui.QVBoxLayout()
        self.setupLayout.setMargin(4)
        self.setupLayout.setObjectName(_fromUtf8("setupLayout"))
        self.headerLbl = QtGui.QLabel(setupDlg)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.headerLbl.setFont(font)
        self.headerLbl.setObjectName(_fromUtf8("headerLbl"))
        self.setupLayout.addWidget(self.headerLbl)
        self.groupBox = QtGui.QGroupBox(setupDlg)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.nameLbl = QtGui.QLabel(self.groupBox)
        self.nameLbl.setObjectName(_fromUtf8("nameLbl"))
        self.verticalLayout.addWidget(self.nameLbl)
        self.nameTxt = QtGui.QLineEdit(self.groupBox)
        self.nameTxt.setObjectName(_fromUtf8("nameTxt"))
        self.verticalLayout.addWidget(self.nameTxt)
        self.testRangeLbl = QtGui.QLabel(self.groupBox)
        self.testRangeLbl.setEnabled(True)
        self.testRangeLbl.setObjectName(_fromUtf8("testRangeLbl"))
        self.verticalLayout.addWidget(self.testRangeLbl)
        self.testRangeHLayout = QtGui.QHBoxLayout()
        self.testRangeHLayout.setContentsMargins(-1, -1, 30, -1)
        self.testRangeHLayout.setObjectName(_fromUtf8("testRangeHLayout"))
        self.fromLbl = QtGui.QLabel(self.groupBox)
        self.fromLbl.setEnabled(False)
        self.fromLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fromLbl.setObjectName(_fromUtf8("fromLbl"))
        self.testRangeHLayout.addWidget(self.fromLbl)
        self.startRangeSpinBox = QtGui.QSpinBox(self.groupBox)
        self.startRangeSpinBox.setEnabled(False)
        self.startRangeSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.startRangeSpinBox.setMinimum(1)
        self.startRangeSpinBox.setObjectName(_fromUtf8("startRangeSpinBox"))
        self.testRangeHLayout.addWidget(self.startRangeSpinBox)
        self.toLbl = QtGui.QLabel(self.groupBox)
        self.toLbl.setEnabled(False)
        self.toLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.toLbl.setObjectName(_fromUtf8("toLbl"))
        self.testRangeHLayout.addWidget(self.toLbl)
        self.endRangeSpinBox = QtGui.QSpinBox(self.groupBox)
        self.endRangeSpinBox.setEnabled(False)
        self.endRangeSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.endRangeSpinBox.setMinimum(1)
        self.endRangeSpinBox.setObjectName(_fromUtf8("endRangeSpinBox"))
        self.testRangeHLayout.addWidget(self.endRangeSpinBox)
        self.verticalLayout.addLayout(self.testRangeHLayout)
        self.statusLbl = QtGui.QLabel(self.groupBox)
        self.statusLbl.setText(_fromUtf8(""))
        self.statusLbl.setObjectName(_fromUtf8("statusLbl"))
        self.verticalLayout.addWidget(self.statusLbl)
        self.testbankDirLbl = QtGui.QLabel(self.groupBox)
        self.testbankDirLbl.setObjectName(_fromUtf8("testbankDirLbl"))
        self.verticalLayout.addWidget(self.testbankDirLbl)
        self.browseLayout = QtGui.QHBoxLayout()
        self.browseLayout.setObjectName(_fromUtf8("browseLayout"))
        self.testbankDirTxt = QtGui.QLineEdit(self.groupBox)
        self.testbankDirTxt.setObjectName(_fromUtf8("testbankDirTxt"))
        self.browseLayout.addWidget(self.testbankDirTxt)
        self.browseBtn = QtGui.QPushButton(self.groupBox)
        self.browseBtn.setObjectName(_fromUtf8("browseBtn"))
        self.browseLayout.addWidget(self.browseBtn)
        self.goBtn = QtGui.QPushButton(self.groupBox)
        self.goBtn.setEnabled(False)
        self.goBtn.setObjectName(_fromUtf8("goBtn"))
        self.browseLayout.addWidget(self.goBtn)
        self.verticalLayout.addLayout(self.browseLayout)
        self.setupLayout.addWidget(self.groupBox)
        self.orLbl = QtGui.QLabel(setupDlg)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.orLbl.setFont(font)
        self.orLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.orLbl.setObjectName(_fromUtf8("orLbl"))
        self.setupLayout.addWidget(self.orLbl)
        self.groupBox_2 = QtGui.QGroupBox(setupDlg)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.prevSessionLbl = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prevSessionLbl.setFont(font)
        self.prevSessionLbl.setObjectName(_fromUtf8("prevSessionLbl"))
        self.verticalLayout_2.addWidget(self.prevSessionLbl)
        self.resumeBtn = QtGui.QPushButton(self.groupBox_2)
        self.resumeBtn.setEnabled(False)
        self.resumeBtn.setCheckable(False)
        self.resumeBtn.setObjectName(_fromUtf8("resumeBtn"))
        self.verticalLayout_2.addWidget(self.resumeBtn)
        self.setupLayout.addWidget(self.groupBox_2)
        self.progressBar = QtGui.QProgressBar(setupDlg)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.setupLayout.addWidget(self.progressBar)
        self.bottomBtnLayout = QtGui.QHBoxLayout()
        self.bottomBtnLayout.setSpacing(50)
        self.bottomBtnLayout.setObjectName(_fromUtf8("bottomBtnLayout"))
        self.aboutBtn = QtGui.QPushButton(setupDlg)
        self.aboutBtn.setObjectName(_fromUtf8("aboutBtn"))
        self.bottomBtnLayout.addWidget(self.aboutBtn)
        self.exitBtn = QtGui.QPushButton(setupDlg)
        self.exitBtn.setObjectName(_fromUtf8("exitBtn"))
        self.bottomBtnLayout.addWidget(self.exitBtn)
        self.setupLayout.addLayout(self.bottomBtnLayout)
        self.gridLayout.addLayout(self.setupLayout, 0, 0, 1, 1)

        self.retranslateUi(setupDlg)
        QtCore.QMetaObject.connectSlotsByName(setupDlg)

    def retranslateUi(self, setupDlg):
        setupDlg.setWindowTitle(_translate("setupDlg", "IEEE Testbank Tool - Setup", None))
        self.headerLbl.setText(_translate("setupDlg", "IEEE Testbank Tool - Setup", None))
        self.groupBox.setTitle(_translate("setupDlg", "Start from Scratch", None))
        self.nameLbl.setText(_translate("setupDlg", "Name:", None))
        self.testRangeLbl.setText(_translate("setupDlg", "Select the testbank directory first, then select your test range!", None))
        self.fromLbl.setText(_translate("setupDlg", "From", None))
        self.toLbl.setText(_translate("setupDlg", "to", None))
        self.testbankDirLbl.setText(_translate("setupDlg", "Testbank Directory:", None))
        self.browseBtn.setText(_translate("setupDlg", "Browse...", None))
        self.goBtn.setText(_translate("setupDlg", "Go >", None))
        self.orLbl.setText(_translate("setupDlg", "- OR -", None))
        self.groupBox_2.setTitle(_translate("setupDlg", "Resume from Before", None))
        self.prevSessionLbl.setText(_translate("setupDlg", "No previous session detected.", None))
        self.resumeBtn.setText(_translate("setupDlg", "Resume from where I left off...", None))
        self.aboutBtn.setText(_translate("setupDlg", "About...", None))
        self.exitBtn.setText(_translate("setupDlg", "Exit", None))

