# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sorting.ui'
#
# Created: Sun Oct 04 14:05:03 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_sortDlg(object):
    def setupUi(self, sortDlg):
        sortDlg.setObjectName(_fromUtf8("sortDlg"))
        sortDlg.resize(539, 714)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(sortDlg.sizePolicy().hasHeightForWidth())
        sortDlg.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(sortDlg)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sortingLayout = QtGui.QVBoxLayout()
        self.sortingLayout.setMargin(4)
        self.sortingLayout.setObjectName(_fromUtf8("sortingLayout"))
        self.headerLbl = QtGui.QLabel(sortDlg)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.headerLbl.setFont(font)
        self.headerLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.headerLbl.setLineWidth(0)
        self.headerLbl.setObjectName(_fromUtf8("headerLbl"))
        self.sortingLayout.addWidget(self.headerLbl)
        self.testRangeLayout = QtGui.QVBoxLayout()
        self.testRangeLayout.setObjectName(_fromUtf8("testRangeLayout"))
        self.testRangeGroupBox = QtGui.QGroupBox(sortDlg)
        self.testRangeGroupBox.setObjectName(_fromUtf8("testRangeGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.testRangeGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lockTestRangeChk = QtGui.QCheckBox(self.testRangeGroupBox)
        self.lockTestRangeChk.setObjectName(_fromUtf8("lockTestRangeChk"))
        self.verticalLayout_3.addWidget(self.lockTestRangeChk)
        self.testRangeHLayout = QtGui.QHBoxLayout()
        self.testRangeHLayout.setContentsMargins(-1, -1, 30, -1)
        self.testRangeHLayout.setObjectName(_fromUtf8("testRangeHLayout"))
        self.fromLbl = QtGui.QLabel(self.testRangeGroupBox)
        self.fromLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fromLbl.setObjectName(_fromUtf8("fromLbl"))
        self.testRangeHLayout.addWidget(self.fromLbl)
        self.startRangeSpinBox = QtGui.QSpinBox(self.testRangeGroupBox)
        self.startRangeSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.startRangeSpinBox.setMinimum(1)
        self.startRangeSpinBox.setObjectName(_fromUtf8("startRangeSpinBox"))
        self.testRangeHLayout.addWidget(self.startRangeSpinBox)
        self.toLbl = QtGui.QLabel(self.testRangeGroupBox)
        self.toLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.toLbl.setObjectName(_fromUtf8("toLbl"))
        self.testRangeHLayout.addWidget(self.toLbl)
        self.endRangeSpinBox = QtGui.QSpinBox(self.testRangeGroupBox)
        self.endRangeSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.endRangeSpinBox.setMinimum(1)
        self.endRangeSpinBox.setObjectName(_fromUtf8("endRangeSpinBox"))
        self.testRangeHLayout.addWidget(self.endRangeSpinBox)
        self.verticalLayout_3.addLayout(self.testRangeHLayout)
        self.testRangeLayout.addWidget(self.testRangeGroupBox)
        self.sortingLayout.addLayout(self.testRangeLayout)
        self.testNavigationGroupBox = QtGui.QGroupBox(sortDlg)
        self.testNavigationGroupBox.setObjectName(_fromUtf8("testNavigationGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.testNavigationGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.openTestBtn = QtGui.QPushButton(self.testNavigationGroupBox)
        self.openTestBtn.setObjectName(_fromUtf8("openTestBtn"))
        self.gridLayout_2.addWidget(self.openTestBtn, 2, 2, 1, 1)
        self.nextTestBtn = QtGui.QPushButton(self.testNavigationGroupBox)
        self.nextTestBtn.setObjectName(_fromUtf8("nextTestBtn"))
        self.gridLayout_2.addWidget(self.nextTestBtn, 2, 3, 1, 1)
        self.firstTestBtn = QtGui.QPushButton(self.testNavigationGroupBox)
        self.firstTestBtn.setObjectName(_fromUtf8("firstTestBtn"))
        self.gridLayout_2.addWidget(self.firstTestBtn, 2, 0, 1, 1)
        self.currentTestHeaderLbl = QtGui.QLabel(self.testNavigationGroupBox)
        self.currentTestHeaderLbl.setObjectName(_fromUtf8("currentTestHeaderLbl"))
        self.gridLayout_2.addWidget(self.currentTestHeaderLbl, 0, 0, 1, 1)
        self.lastTestBtn = QtGui.QPushButton(self.testNavigationGroupBox)
        self.lastTestBtn.setObjectName(_fromUtf8("lastTestBtn"))
        self.gridLayout_2.addWidget(self.lastTestBtn, 2, 4, 1, 1)
        self.prevTestBtn = QtGui.QPushButton(self.testNavigationGroupBox)
        self.prevTestBtn.setObjectName(_fromUtf8("prevTestBtn"))
        self.gridLayout_2.addWidget(self.prevTestBtn, 2, 1, 1, 1)
        self.currentTestLbl = QtGui.QLabel(self.testNavigationGroupBox)
        self.currentTestLbl.setObjectName(_fromUtf8("currentTestLbl"))
        self.gridLayout_2.addWidget(self.currentTestLbl, 1, 0, 1, 4)
        self.sortingLayout.addWidget(self.testNavigationGroupBox)
        self.testMetadataGroupBox = QtGui.QGroupBox(sortDlg)
        self.testMetadataGroupBox.setObjectName(_fromUtf8("testMetadataGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.testMetadataGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.examCommandLayout = QtGui.QHBoxLayout()
        self.examCommandLayout.setObjectName(_fromUtf8("examCommandLayout"))
        self.autofillBtn = QtGui.QPushButton(self.testMetadataGroupBox)
        self.autofillBtn.setObjectName(_fromUtf8("autofillBtn"))
        self.examCommandLayout.addWidget(self.autofillBtn)
        self.revertBtn = QtGui.QPushButton(self.testMetadataGroupBox)
        self.revertBtn.setObjectName(_fromUtf8("revertBtn"))
        self.examCommandLayout.addWidget(self.revertBtn)
        self.saveBtn = QtGui.QPushButton(self.testMetadataGroupBox)
        self.saveBtn.setObjectName(_fromUtf8("saveBtn"))
        self.examCommandLayout.addWidget(self.saveBtn)
        self.verticalLayout_4.addLayout(self.examCommandLayout)
        self.validTestLayout = QtGui.QHBoxLayout()
        self.validTestLayout.setContentsMargins(0, -1, -1, -1)
        self.validTestLayout.setObjectName(_fromUtf8("validTestLayout"))
        self.validTestLbl = QtGui.QLabel(self.testMetadataGroupBox)
        self.validTestLbl.setObjectName(_fromUtf8("validTestLbl"))
        self.validTestLayout.addWidget(self.validTestLbl)
        self.validTestAllGoodRadio = QtGui.QRadioButton(self.testMetadataGroupBox)
        self.validTestAllGoodRadio.setObjectName(_fromUtf8("validTestAllGoodRadio"))
        self.testValidButtonGroup = QtGui.QButtonGroup(sortDlg)
        self.testValidButtonGroup.setObjectName(_fromUtf8("testValidButtonGroup"))
        self.testValidButtonGroup.addButton(self.validTestAllGoodRadio)
        self.validTestLayout.addWidget(self.validTestAllGoodRadio)
        self.validTestWrongTestRadio = QtGui.QRadioButton(self.testMetadataGroupBox)
        self.validTestWrongTestRadio.setObjectName(_fromUtf8("validTestWrongTestRadio"))
        self.testValidButtonGroup.addButton(self.validTestWrongTestRadio)
        self.validTestLayout.addWidget(self.validTestWrongTestRadio)
        self.validTestJunkRadio = QtGui.QRadioButton(self.testMetadataGroupBox)
        self.validTestJunkRadio.setObjectName(_fromUtf8("validTestJunkRadio"))
        self.testValidButtonGroup.addButton(self.validTestJunkRadio)
        self.validTestLayout.addWidget(self.validTestJunkRadio)
        self.verticalLayout_4.addLayout(self.validTestLayout)
        self.classLayout = QtGui.QHBoxLayout()
        self.classLayout.setObjectName(_fromUtf8("classLayout"))
        self.classLbl = QtGui.QLabel(self.testMetadataGroupBox)
        self.classLbl.setObjectName(_fromUtf8("classLbl"))
        self.classLayout.addWidget(self.classLbl)
        self.classTxt = QtGui.QLineEdit(self.testMetadataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classTxt.sizePolicy().hasHeightForWidth())
        self.classTxt.setSizePolicy(sizePolicy)
        self.classTxt.setObjectName(_fromUtf8("classTxt"))
        self.classLayout.addWidget(self.classTxt)
        self.verticalLayout_4.addLayout(self.classLayout)
        self.semesterLayout = QtGui.QHBoxLayout()
        self.semesterLayout.setObjectName(_fromUtf8("semesterLayout"))
        self.semesterLbl = QtGui.QLabel(self.testMetadataGroupBox)
        self.semesterLbl.setObjectName(_fromUtf8("semesterLbl"))
        self.semesterLayout.addWidget(self.semesterLbl)
        self.semesterCBox = QtGui.QComboBox(self.testMetadataGroupBox)
        self.semesterCBox.setObjectName(_fromUtf8("semesterCBox"))
        self.semesterCBox.addItem(_fromUtf8(""))
        self.semesterCBox.addItem(_fromUtf8(""))
        self.semesterCBox.addItem(_fromUtf8(""))
        self.semesterCBox.addItem(_fromUtf8(""))
        self.semesterLayout.addWidget(self.semesterCBox)
        self.yearLbl = QtGui.QLabel(self.testMetadataGroupBox)
        self.yearLbl.setObjectName(_fromUtf8("yearLbl"))
        self.semesterLayout.addWidget(self.yearLbl)
        self.yearSpinBox = QtGui.QSpinBox(self.testMetadataGroupBox)
        self.yearSpinBox.setMinimum(1990)
        self.yearSpinBox.setMaximum(2020)
        self.yearSpinBox.setProperty("value", 2015)
        self.yearSpinBox.setObjectName(_fromUtf8("yearSpinBox"))
        self.semesterLayout.addWidget(self.yearSpinBox)
        self.verticalLayout_4.addLayout(self.semesterLayout)
        self.profLayout = QtGui.QHBoxLayout()
        self.profLayout.setObjectName(_fromUtf8("profLayout"))
        self.profLastNameLbl = QtGui.QLabel(self.testMetadataGroupBox)
        self.profLastNameLbl.setObjectName(_fromUtf8("profLastNameLbl"))
        self.profLayout.addWidget(self.profLastNameLbl)
        self.profLastNameTxt = QtGui.QLineEdit(self.testMetadataGroupBox)
        self.profLastNameTxt.setObjectName(_fromUtf8("profLastNameTxt"))
        self.profLayout.addWidget(self.profLastNameTxt)
        self.profFirstNameLbl = QtGui.QLabel(self.testMetadataGroupBox)
        self.profFirstNameLbl.setObjectName(_fromUtf8("profFirstNameLbl"))
        self.profLayout.addWidget(self.profFirstNameLbl)
        self.profFirstNameTxt = QtGui.QLineEdit(self.testMetadataGroupBox)
        self.profFirstNameTxt.setObjectName(_fromUtf8("profFirstNameTxt"))
        self.profLayout.addWidget(self.profFirstNameTxt)
        self.verticalLayout_4.addLayout(self.profLayout)
        self.typeLayout = QtGui.QHBoxLayout()
        self.typeLayout.setObjectName(_fromUtf8("typeLayout"))
        self.testTypeLbl = QtGui.QLabel(self.testMetadataGroupBox)
        self.testTypeLbl.setObjectName(_fromUtf8("testTypeLbl"))
        self.typeLayout.addWidget(self.testTypeLbl)
        self.testTypeQuizRadio = QtGui.QRadioButton(self.testMetadataGroupBox)
        self.testTypeQuizRadio.setObjectName(_fromUtf8("testTypeQuizRadio"))
        self.testTypeBtnGroup = QtGui.QButtonGroup(sortDlg)
        self.testTypeBtnGroup.setObjectName(_fromUtf8("testTypeBtnGroup"))
        self.testTypeBtnGroup.addButton(self.testTypeQuizRadio)
        self.typeLayout.addWidget(self.testTypeQuizRadio)
        self.testTypeMidtermRadio = QtGui.QRadioButton(self.testMetadataGroupBox)
        self.testTypeMidtermRadio.setObjectName(_fromUtf8("testTypeMidtermRadio"))
        self.testTypeBtnGroup.addButton(self.testTypeMidtermRadio)
        self.typeLayout.addWidget(self.testTypeMidtermRadio)
        self.testTypeFinalRadio = QtGui.QRadioButton(self.testMetadataGroupBox)
        self.testTypeFinalRadio.setObjectName(_fromUtf8("testTypeFinalRadio"))
        self.testTypeBtnGroup.addButton(self.testTypeFinalRadio)
        self.typeLayout.addWidget(self.testTypeFinalRadio)
        self.verticalLayout_4.addLayout(self.typeLayout)
        self.testNumLayout = QtGui.QHBoxLayout()
        self.testNumLayout.setObjectName(_fromUtf8("testNumLayout"))
        self.testNumLbl = QtGui.QLabel(self.testMetadataGroupBox)
        self.testNumLbl.setObjectName(_fromUtf8("testNumLbl"))
        self.testNumLayout.addWidget(self.testNumLbl)
        self.testNumSpinBox = QtGui.QSpinBox(self.testMetadataGroupBox)
        self.testNumSpinBox.setObjectName(_fromUtf8("testNumSpinBox"))
        self.testNumLayout.addWidget(self.testNumSpinBox)
        self.verticalLayout_4.addLayout(self.testNumLayout)
        self.addlExamInfoLayout = QtGui.QHBoxLayout()
        self.addlExamInfoLayout.setObjectName(_fromUtf8("addlExamInfoLayout"))
        self.addlExamInfoLbl = QtGui.QLabel(self.testMetadataGroupBox)
        self.addlExamInfoLbl.setObjectName(_fromUtf8("addlExamInfoLbl"))
        self.addlExamInfoLayout.addWidget(self.addlExamInfoLbl)
        self.addlExamInfoTxt = QtGui.QLineEdit(self.testMetadataGroupBox)
        self.addlExamInfoTxt.setObjectName(_fromUtf8("addlExamInfoTxt"))
        self.addlExamInfoLayout.addWidget(self.addlExamInfoTxt)
        self.verticalLayout_4.addLayout(self.addlExamInfoLayout)
        self.fileNotesLbl = QtGui.QLabel(self.testMetadataGroupBox)
        self.fileNotesLbl.setObjectName(_fromUtf8("fileNotesLbl"))
        self.verticalLayout_4.addWidget(self.fileNotesLbl)
        self.fileNotesTxt = QtGui.QPlainTextEdit(self.testMetadataGroupBox)
        self.fileNotesTxt.setObjectName(_fromUtf8("fileNotesTxt"))
        self.verticalLayout_4.addWidget(self.fileNotesTxt)
        self.sortingLayout.addWidget(self.testMetadataGroupBox)
        self.gridLayout.addLayout(self.sortingLayout, 0, 0, 1, 1)

        self.retranslateUi(sortDlg)
        QtCore.QMetaObject.connectSlotsByName(sortDlg)

    def retranslateUi(self, sortDlg):
        sortDlg.setWindowTitle(_translate("sortDlg", "IEEE Testbank Tool - 1/1000 - ENEE499H_Bob_2015_F_Bob_Midterm.pdf", None))
        self.headerLbl.setText(_translate("sortDlg", "IEEE Testbank Tool", None))
        self.testRangeGroupBox.setTitle(_translate("sortDlg", "Test Range:", None))
        self.lockTestRangeChk.setText(_translate("sortDlg", "Check to lock the test range.", None))
        self.fromLbl.setText(_translate("sortDlg", "From", None))
        self.toLbl.setText(_translate("sortDlg", "to", None))
        self.testNavigationGroupBox.setTitle(_translate("sortDlg", "Test Navigation", None))
        self.openTestBtn.setText(_translate("sortDlg", "Open", None))
        self.nextTestBtn.setText(_translate("sortDlg", ">>", None))
        self.firstTestBtn.setText(_translate("sortDlg", "||<", None))
        self.currentTestHeaderLbl.setText(_translate("sortDlg", "Current Test:", None))
        self.lastTestBtn.setText(_translate("sortDlg", ">||", None))
        self.prevTestBtn.setText(_translate("sortDlg", "<<", None))
        self.currentTestLbl.setText(_translate("sortDlg", "ENEE499H_Bob_2015_F_Bob_Midterm.pdf (1/1000)", None))
        self.testMetadataGroupBox.setTitle(_translate("sortDlg", "Test Metadata", None))
        self.autofillBtn.setText(_translate("sortDlg", "Autofill", None))
        self.revertBtn.setText(_translate("sortDlg", "Revert", None))
        self.saveBtn.setText(_translate("sortDlg", "Save", None))
        self.validTestLbl.setText(_translate("sortDlg", "Is the test valid?", None))
        self.validTestAllGoodRadio.setText(_translate("sortDlg", "All good", None))
        self.validTestWrongTestRadio.setText(_translate("sortDlg", "Wrong Test", None))
        self.validTestJunkRadio.setText(_translate("sortDlg", "Junk", None))
        self.classLbl.setText(_translate("sortDlg", "Class:", None))
        self.semesterLbl.setText(_translate("sortDlg", "Semester:", None))
        self.semesterCBox.setItemText(0, _translate("sortDlg", "Fall", None))
        self.semesterCBox.setItemText(1, _translate("sortDlg", "Winter", None))
        self.semesterCBox.setItemText(2, _translate("sortDlg", "Spring", None))
        self.semesterCBox.setItemText(3, _translate("sortDlg", "Summer", None))
        self.yearLbl.setText(_translate("sortDlg", "Year:", None))
        self.profLastNameLbl.setText(_translate("sortDlg", "Professor Last Name:", None))
        self.profFirstNameLbl.setText(_translate("sortDlg", "Professor First Name:", None))
        self.testTypeLbl.setText(_translate("sortDlg", "Type:", None))
        self.testTypeQuizRadio.setText(_translate("sortDlg", "Quiz", None))
        self.testTypeMidtermRadio.setText(_translate("sortDlg", "Midterm", None))
        self.testTypeFinalRadio.setText(_translate("sortDlg", "Final", None))
        self.testNumLbl.setText(_translate("sortDlg", "Test #:", None))
        self.addlExamInfoLbl.setText(_translate("sortDlg", "Additional Exam Info:", None))
        self.fileNotesLbl.setText(_translate("sortDlg", "File notes:", None))

